%YAML 1.2
---
name: '256x20-test-1'                  # ideally no spaces
gpu: 0                                 # gpu id to process on

dataset: 
  num_chunks: 500000                   # newest nof chunks to parse
  train_ratio: 0.90                    # trainingset ratio
  # For separated test and train data.
  input_train: '/ramdisk/train/' # supports glob
  input_test: '/ramdisk/test/'  # supports glob
  # For a one-shot run with all data in one directory.
  #input: '/work/lc0/data/'

training:
    batch_size: 512                    # training batch
    test_steps: 2000                   # eval test set values after this many steps
    train_avg_report_steps: 1000       # training reports its average values after this many steps.
    total_steps: 10000                 # terminate after these steps
    # checkpoint_steps: 10000          # optional frequency for checkpointing before finish
    shuffle_size: 500000               # size of the shuffle buffer
    lr_values:                         # list of learning rates
        - 0.0075
        - 0.0075
    lr_boundaries:                     # list of boundaries
        - 100
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0             # weight of value loss
    path: '/work/lc0/networks'         # network storage dir

model:
  filters: 256
  residual_blocks: 20
...
