%YAML 1.2
---
name: '320x24-t60'                  # ideally no spaces
gpu: 0                                 # gpu id to process on

dataset: 
  num_chunks: 1000000                   # newest nof chunks to parse
  allow_less_chunks: true
  train_ratio: 0.90                    # trainingset ratio
  # For separated test and train data.
  input_train: '/ramdisk/dev1/train/' # supports glob
  input_test: '/ramdisk/dev1/test/'  # supports glob
  # For a one-shot run with all data in one directory.
  #input: '/work/lc0/data/'

training:
    swa: true
    swa_output: true
    swa_steps: 25
    swa_max_n: 1
    mask_legal_moves: true
    renorm: true
    renorm_max_r: 1.0
    renorm_max_d: 0.0
    q_ratio: 0.2
    max_grad_norm: 2.5
    batch_size: 4096                   # training batch
    num_batch_splits: 16
    test_steps: 125                    # eval test set values after this many steps
    num_test_positions: 80000
    train_avg_report_steps: 25        # training reports its average values after this many steps.
    total_steps: 250                  # terminate after these steps
    warmup_steps: 125
    # checkpoint_steps: 10000          # optional frequency for checkpointing before finish
    shuffle_size: 500000               # size of the shuffle buffer
    lr_values:                         # list of learning rates
        - 0.2
        - 0.2
    lr_boundaries:                     # list of boundaries
        - 100
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 0.5            # weight of value loss
    path: '/work/lc0/dev1/networks'         # network storage dir

model:
  filters: 320
  residual_blocks: 24
  se_ratio: 10
...
